### ISSUE TITLE
Error during the link

### ISSUE THREAD

**Issue by hallucino** [rust3ds/rust3ds-template#20]
Hi,

I got the following error during the final link:
  = note: arm-none-eabi-gcc: error: 3dsx.specs: No such file or directory
          

error: aborting due to previous error

error: Could not compile `rust3ds-template`.

Not sure why but I have the file in /opt/devkitpro/devkitARM/arm-none-eabi/lib/3dsx.specs

**Comment by FenrirWolf** [comment]
Hmm. This is with devkitARM r47, right? And what OS are you running? Do you have the `$DEVKITPRO` and `$DEVKITARM` env vars set?

**Comment by FenrirWolf** [comment]
Also, what does it say if you run `arm-none-eabi-gcc --version`?

**Comment by hallucino** [comment]
Indeed it was due to another arm toolchain :+1:

**Comment by hallucino** [comment]
Thx !!

**Comment by FenrirWolf** [comment]
No problem. I might tweak `.cargo/config` to specifically run `$DEVKITARM/arm-none-eabi/bin/arm-none-eabi-gcc` to avoid this in the future.
