### ISSUE TITLE
Using the latest version of ctru-rs

### ISSUE THREAD

**Issue by kloumpt** [rust3ds/rust3ds-template#8]
Hi, I'm trying to use the latest version of ctru-rs with this template but I get the following error when I try to compile it:

> rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/CodeGen/AsmPrinterDwarfUnit.cpp:724: llvm::DIE\* llvm::DwarfUnit::getOrCreateTypeDIE(const llvm::MDNode*): assertion `Ty == resolve(Ty->getRef()) && "type was not uniqued, possible ODR violation."' failed.

I'm using a local version of ctru-rs  but the problem also occurs when I'm using the git version.
Is there a way to fix this compilation problem ?

The ultimate goal would be to be able to be able to get involved into improving ctru-rs while being able to test it using this template.

I'm using the latest rust nightly with the latest xargo from git and devkitarm 44

Edit: setting lto from true to false in Cargo.toml allowed the compilation to succed, is it ok to disable it?

**Comment by FenrirWolf** [comment]
I ran into this same issue and already changed it in my fork. For some reason it only happens when you're doing a debug build. You should be able to leave it enabled for release builds.

**Comment by Furyhunter** [comment]
This sounds like a compiler bug. Could you try different nightlies and see which one causes the regression?

**Comment by kloumpt** [comment]
@FenrirWolf Yes, I noticed that, I'm now doing as you said and it's working fine
@Furyhunter Ok, I'm going to try that
